export const mockShops = [
  {
    id: "shop1",
    name: "Dairy Mart",
    address: "123 Main St, Cityville",
    phone: "555-123-4567",
    email: "dairymart@example.com",
    contactPerson: "John Smith",
    notes: "Our largest retail partner",
  },
  {
    id: "shop2",
    name: "Fresh Dairy Shop",
    address: "456 Oak Ave, Townsburg",
    phone: "555-987-6543",
    email: "fresh@example.com",
    contactPerson: "Sarah Johnson",
    notes: "Specializes in organic products",
  },
  {
    id: "shop3",
    name: "Milk & More",
    address: "789 Pine Blvd, Villageton",
    phone: "555-456-7890",
    email: "milkmore@example.com",
    contactPerson: "Michael Brown",
    notes: "New partner, expanding quickly",
  },
]

// Mock data for suppliers
export const mockSuppliers = [
  {
    id: "sup1",
    name: "Farm Fresh Dairy",
    address: "101 Rural Route, Farmville",
    phone: "555-111-2222",
    email: "farmfresh@example.com",
    contactPerson: "Robert Farmer",
    category: "dairy",
    isActive: true,
    notes: "Primary milk supplier",
  },
  {
    id: "sup2",
    name: "Sweet Supplies Inc.",
    address: "202 Sugar Lane, Sweetville",
    phone: "555-222-3333",
    email: "sweet@example.com",
    contactPerson: "Linda Sweet",
    category: "ingredients",
    isActive: true,
    notes: "Supplies all sweeteners and flavorings",
  },
  {
    id: "sup3",
    name: "Packaging Pros",
    address: "303 Box Street, Wraptown",
    phone: "555-333-4444",
    email: "packaging@example.com",
    contactPerson: "Tom Boxer",
    category: "packaging",
    isActive: false,
    notes: "Currently resolving quality issues",
  },
  {
    id: "sup4",
    name: "Organic Dairy Farm",
    address: "404 Green Path, Ecoville",
    phone: "555-444-5555",
    email: "organic@example.com",
    contactPerson: "Emma Green",
    category: "dairy",
    isActive: true,
    notes: "Certified organic supplier",
  },
]

// Mock data for products
export const mockProducts = [
  {
    id: "prod1",
    name: "Fresh Whole Milk",
    price: 3.99,
    unit: "liter",
    category: "Milk",
    description: "Fresh pasteurized whole milk, 3.5% fat content",
    image: "/products/milk.jpg",
    inStock: true,
    supplier: "Farm Fresh Dairy",
    costPrice: 2.5,
    sku: "MILK-001",
    barcode: "8901234567890",
    minStock: 50,
    currentStock: 120,
  },
  {
    id: "prod2",
    name: "Greek Yogurt",
    price: 4.49,
    unit: "cup",
    category: "Yogurt",
    description: "Creamy Greek yogurt, plain flavor, 10% protein",
    image: "/products/yogurt.jpg",
    inStock: true,
    supplier: "Organic Dairy Farm",
    costPrice: 3.2,
    sku: "YOGT-001",
    barcode: "8901234567891",
    minStock: 40,
    currentStock: 85,
  },
  {
    id: "prod3",
    name: "Cheddar Cheese",
    price: 5.99,
    unit: "kg",
    category: "Cheese",
    description: "Aged cheddar cheese, medium sharpness, perfect for sandwiches",
    image: "/products/cheese.jpg",
    inStock: true,
    supplier: "Farm Fresh Dairy",
    costPrice: 4.25,
    sku: "CHSE-001",
    barcode: "8901234567892",
    minStock: 20,
    currentStock: 45,
  },
  {
    id: "prod4",
    name: "Salted Butter",
    price: 3.49,
    unit: "pack",
    category: "Butter",
    description: "Creamy salted butter, 250g per pack",
    image: "/products/butter.jpg",
    inStock: false,
    supplier: "Farm Fresh Dairy",
    costPrice: 2.1,
    sku: "BUTR-001",
    barcode: "8901234567893",
    minStock: 30,
    currentStock: 15,
  },
  {
    id: "prod5",
    name: "Chocolate Milk",
    price: 4.29,
    unit: "liter",
    category: "Milk",
    description: "Delicious chocolate flavored milk, kids' favorite",
    image: "/products/chocolate-milk.jpg",
    inStock: true,
    supplier: "Farm Fresh Dairy",
    costPrice: 2.8,
    sku: "MILK-002",
    barcode: "8901234567894",
    minStock: 40,
    currentStock: 65,
  },
  {
    id: "prod6",
    name: "Whipped Cream",
    price: 2.99,
    unit: "can",
    category: "Cream",
    description: "Ready to use whipped cream in a pressurized can",
    image: "/products/whipped-cream.jpg",
    inStock: true,
    supplier: "Farm Fresh Dairy",
    costPrice: 1.75,
    sku: "CREM-001",
    barcode: "8901234567895",
    minStock: 25,
    currentStock: 50,
  },
  {
    id: "prod7",
    name: "Strawberry Yogurt",
    price: 4.79,
    unit: "cup",
    category: "Yogurt",
    description: "Creamy yogurt with real strawberry pieces",
    image: "/products/yogurt.jpg",
    inStock: true,
    supplier: "Organic Dairy Farm",
    costPrice: 3.4,
    sku: "YOGT-002",
    barcode: "8901234567896",
    minStock: 35,
    currentStock: 60,
  },
  {
    id: "prod8",
    name: "Mozzarella Cheese",
    price: 6.49,
    unit: "kg",
    category: "Cheese",
    description: "Fresh mozzarella cheese, perfect for pizza and salads",
    image: "/products/cheese.jpg",
    inStock: true,
    supplier: "Farm Fresh Dairy",
    costPrice: 4.8,
    sku: "CHSE-002",
    barcode: "8901234567897",
    minStock: 15,
    currentStock: 30,
  },
]

// Mock data for sales analytics
export const mockSalesData = [
  { month: "Jan", revenue: 45000, orders: 1200 },
  { month: "Feb", revenue: 52000, orders: 1350 },
  { month: "Mar", revenue: 49000, orders: 1400 },
  { month: "Apr", revenue: 63000, orders: 1650 },
  { month: "May", revenue: 59000, orders: 1500 },
  { month: "Jun", revenue: 68000, orders: 1700 },
  { month: "Jul", revenue: 72000, orders: 1800 },
  { month: "Aug", revenue: 79000, orders: 1950 },
  { month: "Sep", revenue: 75000, orders: 1850 },
  { month: "Oct", revenue: 82000, orders: 2000 },
  { month: "Nov", revenue: 87000, orders: 2100 },
  { month: "Dec", revenue: 96000, orders: 2300 },
]

// Mock data for category distribution
export const mockCategoryData = [
  { name: "Milk", value: 35 },
  { name: "Yogurt", value: 25 },
  { name: "Cheese", value: 20 },
  { name: "Butter", value: 10 },
  { name: "Cream", value: 10 },
]

// Mock data for shop distribution
export const mockShopDistribution = [
  { name: "Dairy Mart", value: 45 },
  { name: "Fresh Dairy Shop", value: 30 },
  { name: "Milk & More", value: 25 },
]

// Mock data for order status
export const mockOrderStatus = [
  { name: "Delivered", value: 65 },
  { name: "In Transit", value: 15 },
  { name: "Processing", value: 12 },
  { name: "Pending", value: 8 },
]

// Mock data for top products
export const mockTopProducts = [
  { name: "Fresh Whole Milk", sales: 12500, growth: 15 },
  { name: "Greek Yogurt", sales: 9800, growth: 22 },
  { name: "Cheddar Cheese", sales: 7600, growth: 8 },
  { name: "Chocolate Milk", sales: 6900, growth: 17 },
  { name: "Strawberry Yogurt", sales: 5400, growth: 12 },
]

// Mock data for orders
export const mockOrders = [
  {
    id: "ORD-001",
    shopId: "shop1",
    shopName: "Dairy Mart",
    date: "2023-05-01",
    status: "DELIVERED",
    items: [
      { productId: "prod1", productName: "Fresh Whole Milk", quantity: 20, price: 3.99, subtotal: 79.8 },
      { productId: "prod3", productName: "Cheddar Cheese", quantity: 5, price: 5.99, subtotal: 29.95 },
    ],
    total: 109.75,
    paymentStatus: "PAID",
    deliveryDate: "2023-05-03",
  },
  {
    id: "ORD-002",
    shopId: "shop2",
    shopName: "Fresh Dairy Shop",
    date: "2023-05-02",
    status: "DELIVERED",
    items: [
      { productId: "prod2", productName: "Greek Yogurt", quantity: 15, price: 4.49, subtotal: 67.35 },
      { productId: "prod5", productName: "Chocolate Milk", quantity: 10, price: 4.29, subtotal: 42.9 },
    ],
    total: 110.25,
    paymentStatus: "PAID",
    deliveryDate: "2023-05-04",
  },
  {
    id: "ORD-003",
    shopId: "shop3",
    shopName: "Milk & More",
    date: "2023-05-02",
    status: "DELIVERED",
    items: [
      { productId: "prod1", productName: "Fresh Whole Milk", quantity: 25, price: 3.99, subtotal: 99.75 },
      { productId: "prod4", productName: "Salted Butter", quantity: 8, price: 3.49, subtotal: 27.92 },
    ],
    total: 127.67,
    paymentStatus: "PAID",
    deliveryDate: "2023-05-04",
  },
  {
    id: "ORD-004",
    shopId: "shop1",
    shopName: "Dairy Mart",
    date: "2023-05-03",
    status: "APPROVED",
    items: [
      { productId: "prod3", productName: "Cheddar Cheese", quantity: 12, price: 5.99, subtotal: 71.88 },
      { productId: "prod6", productName: "Whipped Cream", quantity: 5, price: 2.99, subtotal: 14.95 },
    ],
    total: 86.83,
    paymentStatus: "PAID",
    deliveryDate: "2023-05-05",
  },
  {
    id: "ORD-005",
    shopId: "shop2",
    shopName: "Fresh Dairy Shop",
    date: "2023-05-04",
    status: "SHIPPED",
    items: [
      { productId: "prod7", productName: "Strawberry Yogurt", quantity: 18, price: 4.79, subtotal: 86.22 },
      { productId: "prod8", productName: "Mozzarella Cheese", quantity: 6, price: 6.49, subtotal: 38.94 },
    ],
    total: 125.16,
    paymentStatus: "PAID",
    deliveryDate: "2023-05-06",
  },
  {
    id: "ORD-006",
    shopId: "shop1",
    shopName: "Dairy Mart",
    date: "2023-05-05",
    status: "PENDING",
    items: [
      { productId: "prod2", productName: "Greek Yogurt", quantity: 25, price: 4.49, subtotal: 112.25 },
      { productId: "prod5", productName: "Chocolate Milk", quantity: 15, price: 4.29, subtotal: 64.35 },
    ],
    total: 176.6,
    paymentStatus: "UNPAID",
  },
  {
    id: "ORD-007",
    shopId: "shop3",
    shopName: "Milk & More",
    date: "2023-05-05",
    status: "PENDING",
    items: [
      { productId: "prod1", productName: "Fresh Whole Milk", quantity: 30, price: 3.99, subtotal: 119.7 },
      { productId: "prod3", productName: "Cheddar Cheese", quantity: 10, price: 5.99, subtotal: 59.9 },
    ],
    total: 179.6,
    paymentStatus: "UNPAID",
  },
]
